spring:
  application:
    name: interviewapp
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/interview_app
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  tomcat:
    max-swallow-size: 20MB
  port: 6060
jwt:
  secret: yourSecretKeyForJWTMustBeAtLeast32Chars!
  expirationMs: 86400000